### ISSUE TITLE
Single quotes inside a double-quoted string cause syntax highlighting issues

### ISSUE THREAD

**Issue by spadgos** [Blodwynn/-VSCODE-.soy-language-server-client#2]
![selection_546](https://user-images.githubusercontent.com/426222/47017384-6792d680-d152-11e8-869e-4d68630050d6.png)

Seems like it "opens" a string which is never terminated

**Comment by Blodwynn** [comment]
Thanks for this too! Fix is going with the 3.2.4 release. :)
