### ISSUE TITLE
False positive error when calling a template inside a parameter

### ISSUE THREAD

**Issue by spadgos** [Blodwynn/-VSCODE-.soy-language-server-client#3]
![selection_547](https://user-images.githubusercontent.com/426222/47017526-c9534080-d152-11e8-954e-cafdc428f59e.png)

Error message on hover reads:

```
[ex] {param bar kind="html"}{call .baz /}: Unnecessary closing tag for PARAM opening tag.
```

**Comment by Blodwynn** [comment]
Thanks for the issue! Published a fix for it. 🥂

**Comment by spadgos** [comment]
This one is back again. :)

```
[soy-ext] {param bar kind="html"}{call .baz /}: Missing colon from PARAM declaration.
```

**Comment by Blodwynn** [comment]
Thanks for the info. I'll pick this up asap. :)
