### ISSUE TITLE
Some regressions

### ISSUE THREAD

**Issue by spadgos** [Blodwynn/-VSCODE-.soy-language-server-client#4]
This works:
![selection_550](https://user-images.githubusercontent.com/426222/47023354-d4f93400-d15f-11e8-8276-fb4c4e9cf3bd.png)

But adding a colon here breaks it:
![selection_551](https://user-images.githubusercontent.com/426222/47023347-d1fe4380-d15f-11e8-9da3-9bbc3295ecf9.png)

Also, highlighting of comments doesn't work inside the tag any more (comment should be green here):
![selection_549](https://user-images.githubusercontent.com/426222/47023428-f22e0280-d15f-11e8-90c6-e477edb364ff.png)

**Comment by Blodwynn** [comment]
A fix was released with 3.2.5 release. :)
Thanks for opening this issue!
